// vocab.js - Contains all vocabulary lists for the quiz.

const vocabLists = {
    'lesRapportsCh4': {
        name: "Les Rapports",
        categories: {
            nouns: [
                { french: "une âme sœur", english: "soulmate" },
                { french: "une amitié", english: "friendship" },
                { french: "des commérages", english: "gossip" },
                { french: "un esprit", english: "spirit" },
                { french: "un mariage", english: "wedding/marriage" },
                { french: "un rendez-vous", english: "date" },
                { french: "une responsabilité", english: "responsibility" }
            ],
            verbs: [
                { french: "compter sur", english: "to count on" },
                { french: "draguer", english: "to flirt" },
                { french: "s'engager", english: "to commit" },
                { french: "faire confiance", english: "to trust" },
                { french: "mentir", english: "to lie" },
                { french: "mériter", english: "to be worth" },
                { french: "partager", english: "to share" },
                { french: "poser un lapin", english: "to stand someone up" },
                { french: "quitter quelqu'un", english: "to leave someone" },
                { french: "rompre", english: "to break up (using verb that starts with r)" },
                { french: "casser (avec)", english: "to break up (using verb that starts with c)" },
                { french: "sortir avec", english: "to go out with" },
                { french: "agacer", english: "to annoy (starts with a)" },
                { french: "énerver", english: "to annoy (starts with é)" },
                { french: "aimer", english: "to love" },
                { french: "avoir honte", english: "to be ashamed of" },
                { french: "en avoir marre", english: "to be fed up with" },
                { french: "s'entendre bien", english: "to get along well" },
                { french: "s'entendre mal", english: "to get along badly" },
                { french: "gêner", english: "to bother" },
                { french: "se mettre en colère contre", english: "to get angry with" },
                { french: "ressentir", english: "to feel" },
                { french: "rêver de", english: "to dream of/about" },
                { french: "tomber amoureux", english: "to fall in love (masculine)" },
                { french: "tomber amoureuse", english: "to fall in love (feminine)" },
                { french: "divorcer", english: "to divorce" },
                { french: "se fiancer", english: "to get engaged" },
                { french: "se marier", english: "to get married" },
                { french: "vivre en union libre", english: "to live together" },
                { french: "avoir confiance en soi", english: "to be confident" }
            ],
            adjectives: [
                { french: "accablé", english: "overwhelmed (masculine)" },
                { french: "accablée", english: "overwhelmed (feminine)" },
                { french: "anxieux", english: "anxious (masculine)" },
                { french: "anxieuse", english: "anxious (feminine)" },
                { french: "contrarié", english: "unpleasant (masculine)" },
                { french: "contrariée", english: "unpleasant (feminine)" },
                { french: "déprimé", english: "depressed (masculine)" },
                { french: "déprimée", english: "depressed (feminine)" },
                { french: "enthousiaste", english: "enthusiastic" },
                { french: "fâché", english: "angry (masculine)" },
                { french: "fâchée", english: "angry (feminine)" },
                { french: "inquiet", english: "worried (masculine)" },
                { french: "inquiète", english: "worried (feminine)" },
                { french: "jaloux", english: "jealous (masculine)" },
                { french: "jalouse", english: "jealous (feminine)" },
                { french: "passager", english: "fleeting / temporary (masculine)" },
                { french: "passagère", english: "fleeting / temporary (feminine)" },
                { french: "célibataire", english: "single" },
                { french: "veuf", english: "widower" },
                { french: "veuve", english: "widow" },
                { french: "charmant", english: "charming (masculine)" },
                { french: "charmante", english: "charming (feminine)" },
                { french: "économe", english: "thrifty" },
                { french: "franc", english: "direct (masculine)" },
                { french: "franche", english: "direct (feminine)" },
                { french: "génial", english: "great (masculine)" },
                { french: "géniale", english: "great (feminine)" },
                { french: "honnête", english: "honest" },
                { french: "malhonnête", english: "dishonest" },
                { french: "idéaliste", english: "idealistic" },
                { french: "inoubliable", english: "unforgettable" },
                { french: "mûr", english: "mature" },
                { french: "affectueux", english: "affectionate (masculine)" },
                { french: "affectueuse", english: "affectionate (feminine)" },
                { french: "orgueilleux", english: "proud (masculine)" },
                { french: "orgueilleuse", english: "proud (feminine)" },
                { french: "prudent", english: "careful (masculine)" },
                { french: "prudente", english: "careful (feminine)" },
                { french: "séduisant", english: "attractive (masculine)" },
                { french: "séduisante", english: "attractive (feminine)" },
                { french: "sensible", english: "sensitive" },
                { french: "timide", english: "shy" },
                { french: "tranquille", english: "calm" },
                { french: "fidèle", english: "faithful" },
                { french: "infidèle", english: "unfaithful" }
            ]
        }
    },
    'laFamilleLecon6': {
        name: "La Famille",
        // This list does not have categories, so the sub-list selector will automatically hide.
        terms: [
            { french: "aîné", english: "older (masculine)" },
            { french: "aînée", english: "older (feminine)" },
            { french: "cadet", english: "younger (masculine)" },
            { french: "cadette", english: "younger (feminine)" },
            { french: "un beau-frère", english: "step-brother" },
            { french: "un beau-frère", english: "brother-in-law" },
            { french: "un beau-père", english: "step-father" },
            { french: "un beau-père", english: "father-in-law" },
            { french: "une belle-mère", english: "step-mother" },
            { french: "une belle-mère", english: "mother-in-law" },
            { french: "une belle-sœur", english: "step-sister" },
            { french: "une belle-sœur", english: "sister-in-law" },
            { french: "un cousin", english: "cousin (male)" },
            { french: "une cousine", english: "cousin (female)" },
            { french: "un demi-frère", english: "half-brother" },
            { french: "une demi-sœur", english: "half-sister" },
            { french: "les enfants", english: "children" },
            { french: "un époux", english: "spouse / husband (male)" },
            { french: "une épouse", english: "spouse / wife (female)" },
            { french: "une famille", english: "family" },
            { french: "une femme", english: "wife / woman" },
            { french: "une fille", english: "daughter / girl" },
            { french: "un fils", english: "son" },
            { french: "un frère", english: "brother" },
            { french: "une grand-mère", english: "grandmother" },
            { french: "un grand-père", english: "grandfather" },
            { french: "les grands-parents", english: "grandparents" },
            { french: "un mari", english: "husband" },
            { french: "une mère", english: "mother" },
            { french: "un neveu", english: "nephew" },
            { french: "une nièce", english: "niece" },
            { french: "un oncle", english: "uncle" },
            { french: "les parents", english: "parents" },
            { french: "un père", english: "father" },
            { french: "une petite-fille", english: "granddaughter" },
            { french: "un petit-fils", english: "grandson" },
            { french: "les petits-enfants", english: "grandchildren" },
            { french: "une sœur", english: "sister" },
            { french: "une tante", english: "aunt" },
            { french: "un chat", english: "cat" },
            { french: "un chien", english: "dog" },
            { french: "un oiseau", english: "bird" },
            { french: "un poisson", english: "fish" },
            { french: "un poisson rouge", english: "goldfish" }
        ]
    },
    'lesCoutumesEtLesFetes': {
        name: "Les Coutumes et Les Fêtes",
        terms: [
            { french: "une fête religieuse", english: "a religious holiday" },
            { french: "une fête civile", english: "a civil holiday" },
            { french: "fêter", english: "to celebrate" },
            { french: "un défilé", english: "a parade" },
            { french: "une fête nationale", english: "a national holiday" },
            { french: "une tribune", english: "a grandstand" },
            { french: "un feu d'artifice", english: "a firework display" },
            { french: "un drapeau", english: "a flag" },
            { french: "défiler", english: "to march/parade" },
            { french: "le carnaval", english: "the carnaval" },
            { french: "un char", english: "a float" },
            { french: "lancer", english: "to throw" },
            { french: "des confettis", english: "some confetti" },
            { french: "le bal populaire", english: "the local/village dance" },
            { french: "le Noël", english: "Christmas / Christmastime" },
            { french: "Joyeux Noël", english: "Merry Christmas" },
            { french: "une carte de voeux", english: "a greeting card" },
            { french: "le Père Noël", english: "Santa Claus" },
            { french: "la veille", english: "the eve" },
            { french: "le réveillon", english: "Christmas Eve/New Year's Eve dinner" },
            { french: "un cadeau de Noël", english: "a Christmas present" },
            { french: "chrétien", english: "Christian (masculine)" },
            { french: "chrétienne", english: "Christian (feminine)" },
            { french: "le christianisme", english: "Christianity" },
            { french: "le judaïsme", english: "Judaism" },
            { french: "Hanoukka", english: "Hanukkah" },
            { french: "la fête des Lumières", english: "the Holiday of Lights" },
            { french: "une menorah", english: "a menorah" },
            { french: "juif", english: "Jewish (masculine)" },
            { french: "juive", english: "Jewish (feminine)" },
            { french: "une synagogue", english: "a synagogue" },
            { french: "allumer les bougies", english: "to light the candles" },
            { french: "le jour de l'An", english: "New Year's Day" },
            { french: "le Nouvel An", english: "The New Year" },
            { french: "Bonne année", english: "Happy New Year!" },
            { french: "une mosquée", english: "a mosque" },
            { french: "musulman", english: "Muslim (masculine)" },
            { french: "musulmane", english: "Muslim (feminine)" },
            { french: "l'islam", english: "Islam" },
            { french: "le calendrier lunaire", english: "the lunar calendar" },
            { french: "le croissant lunaire", english: "the Islamic Crescent" },
            { french: "l'aïd el-fitr", english: "Eid al-Fitr" },
            { french: "un mariage religieux", english: "a religious wedding" },
            { french: "un mariage civil", english: "a civil wedding" },
            { french: "le fiancé", english: "the fiancé (male)" },
            { french: "la fiancée", english: "the fiancée (female)" },
            { french: "les fiançailles", english: "the engagement (period)" },
            { french: "une bague de fiançailles", english: "an engagement ring" },
            { french: "le marié", english: "the groom" },
            { french: "la mariée", english: "the bride" },
            { french: "les mariés", english: "the newlyweds" },
            { french: "la demoiselle d'honneur", english: "the maid of honor / matron of honor" },
            { french: "le garçon d'honneur", english: "the best man / the groomsman" },
            { french: "une alliance", english: "a wedding ring" },
            { french: "la mairie", english: "the town hall" },
            { french: "se marier", english: "to get married" },
            { french: "avoir lieu", english: "to take place" },
            { french: "le témoin", english: "the witness (male)" },
            { french: "la témoine", english: "the witness (female)" },
            { french: "la pièce montée", english: "the wedding cake" },
            { french: "une lune de miel", english: "a honeymoon" },
            { french: "une réception", english: "a reception" },
            { french: "féliciter", english: "to congratulate" },
            { french: "se fiancer avec", english: "to get engaged to" },
            { french: "épouser quelqu'un", english: "to marry someone" },
            { french: "être marié avec", english: "to be married to (masculine)" },
            { french: "être mariée avec", english: "to be married to (feminine)" }
        ]
    },
    'laNature': {
    name: "L'Espace Vert",
    categories: {
        nature: [
            { french: "un espace", english: "a space" },
            { french: "les espaces verts", english: "a green space / park" },
            { french: "une espèce", english: "a species" },
            { french: "une espèce menacée", english: "an endangered species" },
            { french: "la nature", english: "the nature" },
            { french: "un pique-nique", english: "a picnic" },
            { french: "une région", english: "a region" },
            { french: "une ressource naturelle", english: "a natural resource" },
            { french: "une vallée", english: "a valley" },
            { french: "une rivière", english: "a river" },
            { french: "un parc naturel", english: "a nature reserve" },
            { french: "un paysage", english: "a landscape / scenery" },
            { french: "une plante", english: "a plant" },
            { french: "une pierre", english: "a stone" },
            { french: "une île", english: "an island" },
            { french: "une forêt tropicale", english: "a rain forest / tropical forest" },
            { french: "une forêt", english: "a forest" },
            { french: "une falaise", english: "a cliff" },
            { french: "un rocher", english: "a rock" },
            { french: "un glacier", english: "a glacier" },
            { french: "une étoile", english: "a star" },
            { french: "une côte", english: "a coast" },
            { french: "un volcan", english: "a volcano" },
            { french: "un sentier", english: "a path" },
            { french: "un lac", english: "a lake" },
            { french: "un fleuve", english: "a river" },
            { french: "un désert", english: "a desert" },
            { french: "un champ", english: "a field" },
            { french: "un bois", english: "the woods" },
            { french: "un arbre", english: "a tree" },
            { french: "le ciel", english: "the sky" },
            { french: "la lune", english: "the moon" },
            { french: "la jungle", english: "the jungle" },
            { french: "l'herbe", english: "the grass" },
            { french: "en plein air", english: "outdoors" },
            { french: "pur", english: "pure (m.)" },
            { french: "pure", english: "pure (f.)" }
        ],
        animaux: [
            { french: "une vache", english: "a cow" },
            { french: "un serpent", english: "a snake" },
            { french: "un lapin", english: "a rabbit" },
            { french: "un écureuil", english: "a squirrel" },
            { french: "une tortue", english: "a turtle" },
            { french: "un singe", english: "a monkey" },
            { french: "un requin", english: "a shark" },
            { french: "un ours", english: "a bear" },
            { french: "l'ours blanc", english: "a polar bear" },
            { french: "un papillon", english: "a butterfly" },
            { french: "une abeille", english: "a bee" },
            { french: "un cerf", english: "a deer" },
            { french: "un loup", english: "a wolf" },
            { french: "un mouton", english: "a sheep" },
            { french: "une chauve-souris", english: "a bat" },
            { french: "un renard", english: "a fox" },
            { french: "un corbeau", english: "a crow" },
            { french: "une grenouille", english: "a frog" },
            { french: "un poisson rouge", english: "a gold fish" },
            { french: "un oiseau", english: "a bird" }
        ],
        ecologie: [
            { french: "l'écologie", english: "ecology" },
            { french: "le sauvetage des habitats naturels", english: "the restoration of habitats" },
            { french: "un écosystème", english: "an ecosystem" },
            { french: "le déboisement", english: "deforestation" },
            { french: "la préservation", english: "preservation" },
            { french: "la chasse", english: "hunting" },
            { french: "l'extinction", english: "extinction" },
            { french: "en voie d'extinction", english: "endangered" },
            { french: "protéger", english: "to protect" },
            { french: "l'écotourisme", english: "ecotourism" }
        ]
    }
    },
    'lEspaceVert': {
    name: "L'Espace Vert - Sauvons la planète",
    categories: {
        verbes: [
            { french: "débrancher", english: "to unplug / disconnect" },
            { french: "agir", english: "to act" },
            { french: "économiser l'énergie", english: "preserve / save energy" },
            { french: "abolir", english: "to abolish" },
            { french: "améliorer", english: "to improve" },
            { french: "augmenter", english: "to increase" },
            { french: "développer", english: "to develop" },
            { french: "diminuer", english: "to decrease" },
            { french: "gaspiller", english: "to waste" },
            { french: "interdire", english: "to forbid / prohibit" },
            { french: "jeter", english: "to throw out" },
            { french: "polluer", english: "to pollute" },
            { french: "prévenir un incendie", english: "to prevent a fire" },
            { french: "préserver", english: "to preserve" },
            { french: "ramasser", english: "to pick up" },
            { french: "recycler", english: "to recycle" },
            { french: "sauver la planète", english: "to save the planet" },
            { french: "être contaminé", english: "to be contaminated (masculine)" },
            { french: "être contaminée", english: "to be contaminated (feminine)" }
        ],
        noms: [
            { french: "le déplacement", english: "movement" },
            { french: "en charge", english: "charging" },
            { french: "le développement durable", english: "sustainable development" },
            { french: "l'assainissement", english: "the cleanup" },
            { french: "l'eau potable", english: "drinking water" },
            { french: "le produit chimique", english: "chemical product" },
            { french: "le logement", english: "housing" },
            { french: "une catastrophe", english: "a disaster / catastrophe" },
            { french: "un nuage de pollution", english: "smog / a pollution cloud" },
            { french: "un glissement de terrain", english: "a landslide" },
            { french: "un emballage en plastique", english: "plastic packaging" },
            { french: "le trou dans la couche d'ozone", english: "the hole in the ozone layer" },
            { french: "le recyclage", english: "recycling" },
            { french: "la réutilisation", english: "reuse" },
            { french: "le réchauffement climatique", english: "global warming" },
            { french: "le ramassage des ordures", english: "garbage collection" },
            { french: "le gaspillage", english: "waste" },
            { french: "le covoiturage", english: "carpooling" },
            { french: "la surpopulation", english: "overpopulation" },
            { french: "l'environnement", english: "the environment" },
            { french: "l'énergie solaire", english: "solar energy" },
            { french: "l'énergie nucléaire", english: "nuclear energy" },
            { french: "l'énergie hydraulique", english: "hydraulic energy" },
            { french: "une éolienne", english: "a windmill" },
            { french: "l'effet de serre", english: "the greenhouse effect" },
            { french: "un désastre", english: "a disaster" },
            { french: "les déchets", english: "trash" },
            { french: "une manifestation", english: "a demonstration / protest" },
            { french: "le nettoyage", english: "cleanup / cleaning" },
            { french: "des déchets toxiques (m.)", english: "toxic waste" },
            { french: "une inondation", english: "a flood" },
            { french: "une loi", english: "a law" },
            { french: "un défenseur de l'environnement", english: "an environmentalist" },
            { french: "une entreprise", english: "an enterprise / company" },
            { french: "une canette", english: "a can" },
            { french: "un carton", english: "a (cardboard) box" },
            { french: "une usine", english: "a factory" },
            { french: "la consommation d'énergie", english: "energy consumption" },
            { french: "une population croissante", english: "a growing population" },
            { french: "une centrale nucléaire", english: "a nuclear plant" }
        ],
        adjectifs: [
            { french: "jetable", english: "disposable / single-use" },
            { french: "pur(e)", english: "pure" },
            { french: "environnemental(e)", english: "environmental(singular)" },
            { french: "environnementaux", english: "environmental(masculine & plural)" },
            { french: "renouvelable", english: "renewable" },
            { french: "écologique", english: "ecological" }
        ],
        expressions: [
            { french: "concernant", english: "concerning..." },
            { french: "au niveau de", english: "when it comes to..." },
            { french: "y compris", english: "including" },
            { french: "avoir accès à", english: "to have access to" },
            { french: "sans doute", english: "probably" },
            { french: "sans aucun doute", english: "definitely" }
        ]
    }
}
};